interfaces:
  access:
  - authentication-protocol:
      __datatype: str
      __label: interfaces/access/authentication-protocol
      __options: []
      __value: PAP
      __widget: text_input
    interface:
      __datatype: interface_auto
      __label: interfaces/access/interface
      __options: []
      __value: ens16.1111
      __widget: text_input
    stream-group-id:
      __datatype: int
      __label: interfaces/access/stream-group-id
      __options:
        __max: 65535
        __min: 0
        __step: 1000
      __value: 1
      __widget: number_input
    type:
      __datatype: str
      __label: interfaces/access/type
      __options:
      - pppoe
      - ipoe
      __value: pppoe
      __widget: selectbox
    username:
      __datatype: str
      __label: interfaces/access/username
      __options: []
      __value: HSI
      __widget: text_input
    vlan-mode:
      __datatype: str
      __label: interfaces/access/vlan-mode
      __options:
      - '1:1'
      - N:1
      __value: N:1
      __widget: selectbox
  mac-modifier:
    __datatype: int
    __label: interfaces/mac-modifier
    __options:
      __max: 255
      __min: 0
    __value: 10
    __widget: slider
  network:
  - address:
      __datatype: str
      __label: interfaces/network/address
      __options: []
      __value: 210.210.210.2/24
      __widget: text_input
    gateway:
      __datatype: str
      __label: interfaces/network/gateway
      __options: []
      __value: 210.210.210.1
      __widget: text_input
    interface:
      __datatype: interface_auto
      __label: interfaces/network/interface
      __options: []
      __value: ens17.1111
      __widget: text_input
ppp:
  authentication:
    password:
      __datatype: str
      __label: ppp/authentication/password
      __options: []
      __value: svtech@123
      __widget: text_input
    retry:
      __datatype: str
      __label: ppp/authentication/retry
      __options: []
      __value: '30'
      __widget: text_input
    timeout:
      __datatype: str
      __label: ppp/authentication/timeout
      __options: []
      __value: '2'
      __widget: text_input
    username:
      __datatype: str
      __label: ppp/authentication/username
      __options: []
      __value: HSI-IPv4_{session-global}
      __widget: text_input
  mru:
    __datatype: int
    __label: ppp/mru
    __options:
      __max: 65535
      __min: 1
      __step: 1000
    __value: 1492
    __widget: number_input
pppoe:
  reconnect:
    __datatype: bool
    __label: pppoe/reconnect
    __options:
    - true
    - false
    __value: true
    __widget: selectbox
  session-time:
    __datatype: str
    __label: pppoe/session-time
    __options: []
    __value: '0'
    __widget: text_input
sessions:
  count:
    __datatype: str
    __label: sessions/count
    __options: []
    __value: '1'
    __widget: text_input
streams:
- direction:
    __datatype: str
    __label: streams/direction
    __options:
    - both
    - upstream
    - downstream
    __value: downstream
    __widget: selectbox
  name:
    __datatype: str
    __label: streams/name
    __options: []
    __value: HSI_IPv4
    __widget: text_input
  pps:
    __datatype: str
    __label: streams/pps
    __options: []
    __value: '1000'
    __widget: text_input
  stream-group-id:
    __datatype: str
    __label: streams/stream-group-id
    __options: []
    __value: '1'
    __widget: text_input
  type:
    __datatype: str
    __label: streams/type
    __options:
    - ipv4
    - ipv6
    - ipv6pd
    __value: ipv4
    __widget: selectbox
