interfaces:
  access:
  - address:
      __datatype: str
      __label: interfaces/access/address
      __options: []
      __value: 192.168.6.2
      __widget: text_input
    address-iter:
      __datatype: str
      __label: interfaces/access/address-iter
      __options: []
      __value: 0.0.0.1
      __widget: text_input
    gateway:
      __datatype: str
      __label: interfaces/access/gateway
      __options: []
      __value: 192.168.6.1
      __widget: text_input
    interface:
      __datatype: interface_auto
      __label: interfaces/access/interface
      __options: []
      __value: ens16.1511
      __widget: text_input
    ipv6:
      __datatype: bool
      __label: interfaces/access/ipv6
      __options:
      - true
      - false
      __value: false
      __widget: selectbox
    stream-group-id:
      __datatype: int
      __label: interfaces/access/stream-group-id
      __options:
        __max: 65535
        __min: 0
        __step: 1000
      __value: 24
      __widget: number_input
    type:
      __datatype: str
      __label: interfaces/access/type
      __options:
      - pppoe
      - ipoe
      __value: ipoe
      __widget: selectbox
    vlan-mode:
      __datatype: str
      __label: interfaces/access/vlan-mode
      __options:
      - '1:1'
      - N:1
      __value: N:1
      __widget: selectbox
  io-slots:
    __datatype: str
    __label: interfaces/io-slots
    __options: []
    __value: '65535'
    __widget: text_input
  network:
  - address:
      __datatype: str
      __label: interfaces/network/address
      __options: []
      __value: 192.168.5.6/30
      __widget: text_input
    gateway:
      __datatype: str
      __label: interfaces/network/gateway
      __options: []
      __value: 192.168.5.5
      __widget: text_input
    interface:
      __datatype: interface_auto
      __label: interfaces/network/interface
      __options: []
      __value: ens17.1512
      __widget: text_input
  rx-threads:
    __datatype: str
    __label: interfaces/rx-threads
    __options: []
    __value: '5'
    __widget: text_input
  tx-threads:
    __datatype: str
    __label: interfaces/tx-threads
    __options: []
    __value: '5'
    __widget: text_input
sessions:
  count:
    __datatype: str
    __label: sessions/count
    __options: []
    __value: '100'
    __widget: text_input
streams:
- Gbps:
    __datatype: float
    __label: streams/Gbps
    __options:
      __max: 100.0
      __min: 0.0
      __step: 1.0
    __value: 1.0
    __widget: number_input
  direction:
    __datatype: str
    __label: streams/direction
    __options:
    - both
    - upstream
    - downstream
    __value: both
    __widget: selectbox
  length:
    __datatype: int
    __label: streams/length
    __options:
      __max: 9000
      __min: 76
      __step: 100
    __value: 3936
    __widget: number_input
  name:
    __datatype: str
    __label: streams/name
    __options: []
    __value: DIEPNK_TEST_LOOP_MPC8E
    __widget: text_input
  network-interface:
    __datatype: interface_auto
    __label: streams/network-interface
    __options: []
    __value: ens17.1512
    __widget: text_input
  pps:
    __datatype: str
    __label: streams/pps
    __options: []
    __value: '1000'
    __widget: text_input
  stream-group-id:
    __datatype: str
    __label: streams/stream-group-id
    __options: []
    __value: '24'
    __widget: text_input
  ttl:
    __datatype: int
    __label: streams/ttl
    __options:
      __max: 255
      __min: 0
      __step: 1
    __value: 246
    __widget: number_input
  type:
    __datatype: str
    __label: streams/type
    __options:
    - ipv4
    - ipv6
    - ipv6pd
    __value: ipv4
    __widget: selectbox
